# Generated by Django 4.1.7 on 2023-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_PHC',
            new_name='is_customer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='district',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_ashaworker',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_hospital',
        ),
    ]
