# Generated by Django 4.1.7 on 2023-03-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_remove_account_address_remove_account_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
