# Generated by Django 4.1.7 on 2023-03-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
