# Generated by Django 4.1.7 on 2023-03-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
