# Generated by Django 4.1.7 on 2023-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_remove_customer_contact_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exshowroomprice', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('fuelfuelcapacity', models.CharField(blank=True, max_length=200)),
                ('fueltype', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='product')),
                ('image2', models.ImageField(blank=True, upload_to='product')),
                ('image3', models.ImageField(blank=True, upload_to='product')),
                ('image4', models.ImageField(blank=True, upload_to='product')),
                ('image5', models.ImageField(blank=True, upload_to='product')),
                ('image6', models.ImageField(blank=True, upload_to='product')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('name',),
            },
        ),
    ]
