# Generated by Django 4.1.7 on 2023-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0012_food_login_food_registration_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
                'ordering': ('username',),
            },
        ),
        migrations.RemoveField(
            model_name='food_registration',
            name='user',
        ),
        migrations.DeleteModel(
            name='food_login',
        ),
        migrations.DeleteModel(
            name='food_registration',
        ),
    ]
