# Generated by Django 4.1.7 on 2023-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0014_remove_vehicles_image1_remove_vehicles_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='images',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
