# Generated by Django 4.1.7 on 2023-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_remove_vehicles_images_vehicles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='image1',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image2',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image3',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image4',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image5',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image6',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='stock',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
