# Generated by Django 4.1.7 on 2023-03-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0016_vehicles_image1_vehicles_image2_vehicles_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='stock',
        ),
    ]
