# Generated by Django 4.1.7 on 2023-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0017_remove_vehicles_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
