# Generated by Django 4.1.7 on 2023-03-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0018_alter_vehicles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_drive',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customername', to='carapp.customer'),
        ),
        migrations.CreateModel(
            name='showroom_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(max_length=100, null=True)),
                ('Contact', models.BigIntegerField(default=0)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('visitdate', models.DateField(null=True)),
                ('visittime', models.TimeField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitername', to='carapp.customer')),
            ],
            options={
                'verbose_name': 'showroom_visit',
                'verbose_name_plural': 'showroom_visit',
                'ordering': ('carmodel',),
            },
        ),
    ]
