# Generated by Django 4.1.7 on 2023-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0019_alter_test_drive_username_showroom_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='brochure',
            field=models.FileField(blank=True, upload_to='product'),
        ),
    ]
