# Generated by Django 4.1.7 on 2023-03-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0021_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('loan_tenure', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('emi_amount', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.bank')),
            ],
        ),
    ]
