# Generated by Django 4.1.7 on 2023-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0022_bank_carloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='varient1',
            field=models.TextField(blank=True),
        ),
    ]
