# Generated by Django 4.1.7 on 2023-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0023_vehicles_varient1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='varient1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
