# Generated by Django 4.1.7 on 2023-03-31 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0024_alter_vehicles_varient1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carapp.vehicles')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product gallery',
            },
        ),
    ]
