# Generated by Django 4.1.7 on 2023-03-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0025_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image6',
        ),
    ]
