# Generated by Django 4.1.7 on 2023-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0026_remove_vehicles_image_remove_vehicles_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
