# Generated by Django 4.1.7 on 2023-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0027_vehicles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='banner',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
