# Generated by Django 4.1.7 on 2023-04-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0029_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='carapp.staff'),
        ),
    ]
