# Generated by Django 4.1.7 on 2023-04-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0030_staff_staff_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_assigned',
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carapp.customer'),
        ),
    ]
