# Generated by Django 4.1.7 on 2023-04-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0031_remove_staff_staff_assigned_alter_staff_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
