# Generated by Django 4.1.7 on 2023-04-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0033_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carapp.customer'),
        ),
    ]
