# Generated by Django 4.1.7 on 2023-04-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0034_staff_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='cname',
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.customer')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Assignments',
            },
        ),
    ]
