# Generated by Django 4.1.7 on 2023-04-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0035_remove_staff_cname_staffassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('staffname',), 'verbose_name': 'staff', 'verbose_name_plural': 'staffs'},
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='staffname',
        ),
    ]
