# Generated by Django 4.1.7 on 2023-04-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carapp', '0036_alter_staff_options_rename_username_staff_staffname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom_visit',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test_drive',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customername', to=settings.AUTH_USER_MODEL),
        ),
    ]
